### ISSUE TITLE
Support Encrypted SMS

### ISSUE THREAD

**Issue by ThePreviousOne** [try2codesecure/ShellMS#10]
I use https://github.com/SilenceIM/Silence as my messaging app. To have this functionality in ShellMS would be amazing IMO

**Comment by try2codesecure** [comment]
Hello. Very good idea. If you like to take part of the development process, feel free to do so.

**Comment by ThePreviousOne** [comment]
Id love too. 
However I though I am a decent Java dev I struggle at navigation of other peoples work, do you mind if I come here with those questions?
