### ISSUE TITLE
Sms send just 1 word

### ISSUE THREAD

**Issue by aTastyCookie** [try2codesecure/ShellMS#11]
Sms send just 1 word

**Comment by try2codesecure** [comment]
Hello. I also got this behaviour sometimes. I encapsulate the message with 3 quotes to prevent this. =>  $  sendsms-script.sh "NUMBER-DOUBLE-QOUTED" "'TEXT-DOUBLE-AND-SINGLE-QUOTED'" 
I always use the "template_sendsms_multiple-contacts.sh" script.

**Comment by aTastyCookie** [comment]
I fix it, u need use \ before spaces and another special symbols :)
