### ISSUE TITLE
Build instructions for those of us who are android challenged

### ISSUE THREAD

**Issue by rexroni** [try2codesecure/ShellMS#17]
I had this app on my phone (loved it!!), I lost my phone, I got a new phone, and couldn't find it in the Fdriod repositories.  I am not sure what happened.  But hey, it's FOSS so I'll just build it from source.

But... I do not know how to build even a simple android project without instructions, because I am a C developer and not a mobile developer.  Would it be possible to add command-line build instructions to README?

**Comment by try2codesecure** [comment]
Sorry, i have neglected the app for a while. I changed the build environment to gradle (IntelliJ IDEA). New version is available on f-droid.
