### ISSUE TITLE
Change package name to something less official

### ISSUE THREAD

**Issue by bmintz** [try2codesecure/ShellMS#5]
Currently the package name is com.android.shellms, which is discouraged (unless you have control over android.com!).

I propose changing the package name to either a domain name you own, or to io.github.try2codesecure.shellms.

Of course, this would require that users re-install the new ShellMS, so it would also have to be re-added to F-Droid. The old app could then be deprecated by saying so on its description.

**Comment by try2codesecure** [comment]
You're right. I avoided this a long time, but should be done soon. I'll update the source and request a change in the f-droid store. thanks.

**Comment by bmintz** [comment]
rip
